# Generated by Django 5.2.12 on 2026-03-17 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAccountLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_until', models.DateTimeField(help_text='Expiry of the lock. Login is rejected until this time passes.')),
                ('reason', models.CharField(blank=True, default='Too many failed login attempts.', help_text='Human-readable reason for the lock.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Account Lock',
                'verbose_name_plural': 'Account Locks',
                'db_table': 'auth_account_lock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address used in this login attempt.', max_length=255)),
                ('ip_address', models.CharField(help_text='Source IP address of the request.', max_length=45)),
                ('attempt_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], help_text='Whether the attempt succeeded or failed.', max_length=10)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'db_table': 'auth_login_attempt',
                'ordering': ['-attempt_time'],
            },
        ),
        migrations.CreateModel(
            name='AuthOTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Target email the OTP was sent to.', max_length=255)),
                ('otp_code', models.CharField(help_text='The OTP value (plain or hashed). Never log this field.', max_length=10)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login'), ('PASSWORD_RESET', 'Password Reset'), ('EMAIL_VERIFICATION', 'Email Verification')], help_text='What this OTP is authorising.', max_length=25)),
                ('expires_at', models.DateTimeField(help_text='Hard expiry timestamp. Must ALWAYS be checked before accepting OTP.')),
                ('is_verified', models.BooleanField(default=False, help_text='True = consumed. A verified OTP must never be accepted again.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'db_table': 'auth_otp_verification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthPasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(help_text='Argon2/bcrypt hash of a previously used password.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Password History',
                'verbose_name_plural': 'Password History',
                'db_table': 'auth_password_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthPasswordPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_key', models.CharField(help_text='Machine-readable policy key. Must be unique.', max_length=100, unique=True)),
                ('policy_value', models.CharField(help_text='String value. Cast to correct type in service layer.', max_length=255)),
                ('description', models.CharField(blank=True, default='', help_text='Human-readable description of this policy rule.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive policies are ignored by PasswordPolicyService.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Password Policy',
                'verbose_name_plural': 'Password Policies',
                'db_table': 'auth_password_policy',
                'ordering': ['policy_key'],
            },
        ),
        migrations.CreateModel(
            name='AuthSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='JWT JTI claim or session UUID. Unique per session.', max_length=255, unique=True)),
                ('ip_address', models.CharField(help_text='IPv4 or IPv6 address at login time.', max_length=45)),
                ('user_agent', models.CharField(blank=True, help_text='Browser / client user agent string.', max_length=500, null=True)),
                ('login_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of successful login.')),
                ('logout_at', models.DateTimeField(blank=True, help_text='Timestamp of logout. NULL = session still active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False on logout or token revocation.')),
            ],
            options={
                'verbose_name': 'Session Log',
                'verbose_name_plural': 'Session Logs',
                'db_table': 'auth_session_log',
                'ordering': ['-login_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='E.164 format recommended, e.g. +919876543210.', max_length=20, null=True)),
                ('profile_image_url', models.CharField(blank=True, help_text="URL to the user's profile image.", max_length=500, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Prefer not to say')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'auth_user_profile',
            },
        ),
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(help_text='Primary identifier used for login.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Unset to soft-delete a user without removing the record.'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Grants access to Django admin site.'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(help_text='Display name / handle. 3-150 characters.', max_length=150, unique=True),
        ),
        migrations.AddIndex(
            model_name='authuser',
            index=models.Index(fields=['is_active'], name='idx_auth_user_active'),
        ),
        migrations.AddField(
            model_name='authaccountlock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_locks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='authloginattempt',
            index=models.Index(fields=['email'], name='idx_auth_login_email'),
        ),
        migrations.AddIndex(
            model_name='authloginattempt',
            index=models.Index(fields=['ip_address'], name='idx_auth_login_ip'),
        ),
        migrations.AddIndex(
            model_name='authloginattempt',
            index=models.Index(fields=['attempt_time'], name='idx_auth_login_time'),
        ),
        migrations.AddField(
            model_name='authotpverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authpasswordhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='authpasswordpolicy',
            index=models.Index(fields=['policy_key'], name='idx_pw_policy_key'),
        ),
        migrations.AddIndex(
            model_name='authpasswordpolicy',
            index=models.Index(fields=['is_active'], name='idx_pw_policy_active'),
        ),
        migrations.AddField(
            model_name='authsessionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='authaccountlock',
            index=models.Index(fields=['user'], name='idx_account_lock_user'),
        ),
        migrations.AddIndex(
            model_name='authaccountlock',
            index=models.Index(fields=['locked_until'], name='idx_account_lock_until'),
        ),
        migrations.AddIndex(
            model_name='authotpverification',
            index=models.Index(fields=['user', 'purpose'], name='idx_otp_user_purpose'),
        ),
        migrations.AddIndex(
            model_name='authotpverification',
            index=models.Index(fields=['expires_at'], name='idx_otp_expires_at'),
        ),
        migrations.AddIndex(
            model_name='authpasswordhistory',
            index=models.Index(fields=['user'], name='idx_pw_history_user_id'),
        ),
        migrations.AddIndex(
            model_name='authsessionlog',
            index=models.Index(fields=['user', 'is_active'], name='idx_session_user_active'),
        ),
        migrations.AddIndex(
            model_name='authsessionlog',
            index=models.Index(fields=['session_key'], name='idx_session_key'),
        ),
        migrations.AddIndex(
            model_name='authsessionlog',
            index=models.Index(fields=['ip_address'], name='idx_session_ip'),
        ),
    ]
