# Generated by Django 5.2.12 on 2026-03-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_security', '0002_authaccountlock_authloginattempt_authotpverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the email was successfully verified.', null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='True if the user has verified their email via OTP.'),
        ),
    ]
