# Generated by Django 5.2.12 on 2026-03-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, help_text='ID of the user who performed the action. NULL = system action.', null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PERMISSION_CHANGE', 'Permission Change'), ('CONFIG_CHANGE', 'Config Change'), ('PASSWORD_CHANGE', 'Password Change'), ('ACCOUNT_LOCK', 'Account Lock'), ('ACCOUNT_UNLOCK', 'Account Unlock')], help_text='Type of action performed.', max_length=100)),
                ('module', models.CharField(help_text='App/module that generated this log entry.', max_length=50)),
                ('entity_type', models.CharField(blank=True, default='', help_text="The model/resource being acted on, e.g. 'SystemConfig'.", max_length=100)),
                ('entity_id', models.CharField(blank=True, default='', help_text='PK or identifier of the entity.', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='JSON-serialised before-state.', null=True)),
                ('new_value', models.TextField(blank=True, help_text='JSON-serialised after-state.', null=True)),
                ('ip_address', models.CharField(blank=True, help_text='IPv4 or IPv6 address of the requester.', max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='idx_audit_user_id'), models.Index(fields=['action'], name='idx_audit_action'), models.Index(fields=['module'], name='idx_audit_module'), models.Index(fields=['created_at'], name='idx_audit_created_at')],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(db_index=True, help_text="Unique feature key, e.g. 'otp_login'.", max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_enabled', models.BooleanField(default=False, help_text='Master on/off toggle for this feature.')),
                ('target_scope', models.CharField(choices=[('GLOBAL', 'Global'), ('ROLE', 'Role'), ('DEPARTMENT', 'Department')], default='GLOBAL', help_text='Scope at which this flag applies.', max_length=20)),
                ('rollout_percentage', models.PositiveSmallIntegerField(default=100, help_text='Percentage of target scope that sees this feature (0-100).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'db_table': 'feature_flag',
                'ordering': ['feature_key'],
                'indexes': [models.Index(fields=['feature_key'], name='idx_feature_flag_key'), models.Index(fields=['is_enabled'], name='idx_feature_flag_enabled')],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(db_index=True, help_text='Unique configuration key, e.g. OTP_EXPIRY_SECONDS', max_length=100, unique=True)),
                ('config_value', models.TextField(help_text='Raw string value; cast to correct type via value_type.')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', help_text='The data type of config_value.', max_length=20)),
                ('config_group', models.CharField(blank=True, default='', help_text="Logical grouping, e.g. 'auth', 'email'.", max_length=50)),
                ('description', models.CharField(blank=True, default='', help_text='Human-readable description of this config key.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive configs are ignored by config_service.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Config',
                'verbose_name_plural': 'System Configs',
                'db_table': 'system_config',
                'ordering': ['config_group', 'config_key'],
                'indexes': [models.Index(fields=['config_key'], name='idx_system_config_key'), models.Index(fields=['config_group'], name='idx_system_config_group'), models.Index(fields=['is_active'], name='idx_system_config_active')],
            },
        ),
        migrations.CreateModel(
            name='SystemEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text="Short machine-readable event type, e.g. 'OTP_SEND_FAILURE'.", max_length=100)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('module', models.CharField(help_text='App/component that generated this event.', max_length=100)),
                ('message', models.TextField(help_text='Human-readable description of the event.')),
                ('payload', models.JSONField(blank=True, help_text='Additional structured data (request context, error details, etc.).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Event Log',
                'verbose_name_plural': 'System Event Logs',
                'db_table': 'system_event_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity'], name='idx_event_severity'), models.Index(fields=['module'], name='idx_event_module'), models.Index(fields=['event_type'], name='idx_event_type'), models.Index(fields=['created_at'], name='idx_event_created_at')],
            },
        ),
    ]
